# Generated by Django 3.0.5 on 2020-05-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_info',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Sokak-Apartman'),
        ),
        migrations.DeleteModel(
            name='AddressInfo',
        ),
    ]
