# Generated by Django 3.0.5 on 2020-05-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200503_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon2'),
        ),
    ]
