# Generated by Django 3.0.5 on 2020-05-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20200503_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='distribution_unit',
            field=models.CharField(choices=[('piece', 'adet'), ('liter', 'litre'), ('kilogram', 'kg'), ('kangal', 'kangal')], default='piece', max_length=30),
        ),
    ]
