# Generated by Django 3.0.5 on 2020-05-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderproduct_distribution_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
