# Generated by Django 3.0.5 on 2020-05-04 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20200504_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Customer', verbose_name='Müşteri Adı'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_day',
            field=models.CharField(choices=[('Sunday', 'Pazartesi'), ('Tuesday', 'Salı'), ('Wednesday', 'Çarşamba'), ('Thursday', 'Perşembe'), ('Friday', 'Cuma'), ('Saturday', 'Cumartesi'), ('Monday', 'Pazar')], default='Monday', max_length=50, verbose_name='Dağıtım Günü'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='order.OrderProduct', to='order.Product', verbose_name='Ürünler'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0.0, verbose_name='Toplam Tutar'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='distribution_unit',
            field=models.CharField(choices=[('piece', 'adet'), ('liter', 'litre'), ('kilogram', 'kg'), ('kangal', 'kangal')], default='piece', max_length=30, verbose_name='Dağıtım Birimi'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Sipariş'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Product', verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.FloatField(verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Category', verbose_name='Ürün Kategorisi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='distribution_unit',
            field=models.CharField(choices=[('piece', 'adet'), ('liter', 'litre'), ('kilogram', 'kg'), ('kangal', 'kangal')], max_length=255, verbose_name='Dağıtım Birimi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Fiyatı'),
        ),
    ]
