# Generated by Django 3.0.5 on 2020-05-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20200504_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(default='', verbose_name='Notlar'),
        ),
    ]
