# Generated by Django 3.0.5 on 2020-05-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_day',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Teslimat Tarihi'),
        ),
    ]
