# Generated by Django 3.0.5 on 2020-05-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20200504_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=50, verbose_name='İnstagram Kullanıcı Adı'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_instagram',
            field=models.BooleanField(default=False),
        ),
    ]
