# Generated by Django 3.0.5 on 2020-05-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20200508_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='instagram_username',
            field=models.CharField(blank=True, help_text='Kullanıcı Adı', max_length=50, verbose_name='Kullanıcı Adı'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_instagram',
            field=models.BooleanField(default=False, verbose_name='İnstagram?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(default='', max_length=50, verbose_name='Notlar'),
        ),
    ]
