# Generated by Django 3.0.5 on 2020-05-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20200508_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category']},
        ),
        migrations.AlterField(
            model_name='order',
            name='instagram_username',
            field=models.CharField(blank=True, help_text='Kullanıcı Adı', max_length=50, null=True),
        ),
    ]
