# Generated by Django 3.0.5 on 2020-05-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20200509_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='distribution_unit',
            field=models.CharField(choices=[('piece', 'Adet'), ('liter', 'LT'), ('kilogram', 'KG'), ('kangal', 'Kangal')], default='piece', max_length=30, verbose_name='Dağıtım Birimi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='distribution_unit',
            field=models.CharField(choices=[('piece', 'Adet'), ('liter', 'LT'), ('kilogram', 'KG'), ('kangal', 'Kangal')], max_length=255, verbose_name='Dağıtım Birimi'),
        ),
    ]
