# Generated by Django 3.0.5 on 2020-05-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20200512_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_money',
            field=models.FloatField(default=0.0),
        ),
    ]
