# Generated by Django 3.0.5 on 2020-05-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_order_received_money'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProduct',
            new_name='OrderItem',
        ),
    ]
