# Generated by Django 3.0.5 on 2020-05-12 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_auto_20200513_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_status',
            new_name='is_delivered',
        ),
    ]
