# Generated by Django 3.0.5 on 2020-05-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_auto_20200513_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
