# Generated by Django 3.0.5 on 2020-06-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_remove_orderitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['phone1']},
        ),
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_debt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Alış Fiyatı'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Nakit'), (2, 'EFT')], null=True, verbose_name='Ödeme Şekli'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
