# Generated by Django 3.0.5 on 2020-05-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_remove_orderitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone1',
            field=models.CharField(max_length=50, unique=True, verbose_name='Telefon1'),
        ),
    ]
