# Generated by Django 3.0.5 on 2020-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_auto_20200528_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['phone1']},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Nakit'), (2, 'EFT')], null=True, verbose_name='Ödeme Şekli'),
        ),
    ]
