# Generated by Django 3.0.5 on 2020-06-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_auto_20200605_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
