# Generated by Django 3.0.5 on 2020-06-10 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_auto_20200610_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.9)], verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Fiyatı'),
        ),
    ]
