# Generated by Django 3.0.5 on 2020-06-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_delete_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Alış Fiyatı'),
        ),
    ]
