# Generated by Django 3.0.5 on 2020-06-11 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_auto_20200610_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Miktar'),
        ),
    ]
