# Generated by Django 3.0.5 on 2020-06-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_auto_20200605_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remaining_debt',
            field=models.FloatField(default=0.0),
        ),
    ]
