# Generated by Django 3.0.5 on 2020-06-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_auto_20200611_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Notlar'),
        ),
    ]
