# Generated by Django 3.0.5 on 2020-06-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_customer_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nick',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
