# Generated by Django 3.0.5 on 2020-06-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_auto_20200611_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
