# Generated by Django 3.0.5 on 2020-06-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_order_service_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone1',
            field=models.CharField(max_length=50, unique=True, verbose_name='Telefon1'),
        ),
    ]
