# Generated by Django 3.0.5 on 2020-08-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_auto_20200818_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'Bekleniyor'), ('buyed', 'Satinalindi'), ('deleted', 'Silindi')], default='waiting', max_length=15),
        ),
    ]
