# Generated by Django 3.0.5 on 2020-08-20 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_auto_20200819_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone1',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+123456789'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon1'),
        ),
    ]
