# Generated by Django 3.0.5 on 2020-08-28 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_auto_20200820_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sokak-Apartman'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone1',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Lütfen geçerli bir telefon numarası giriniz.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon Numarası'),
        ),
    ]
